#!/usr/bin/env bash
# script that displays information about domains

display_subdomain_info() {
    line=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')

    echo "$2 $line" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

domain="$1"
subdomain="$2"

if [ -z "$subdomain" ]; then
    display_subdomain_info "$domain" "www"
    display_subdomain_info "$domain" "lb-01"
    display_subdomain_info "$domain" "web-01"
    display_subdomain_info "$domain" "web-02"
else
    display_subdomain_info "$domain" "$subdomain"
fi
