#!/usr/bin/env bash
# installs nginx

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow "Nginx HTTP"
sudo chown -R "$USER":"$USER" /var/www/html/index.nginx-debian.html
sudo echo "Hello World" | sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx restart
