#!/usr/bin/env bash
# Configure your Nginx server to redirect to another page

sudo apt-get update
sudo apt-get install -y nginx
sudo ufw allow "Nginx HTTP"
sudo mkdir -p /etc/nginx/html
sudo chmod -R 755 /var/www
sudo echo "Hello World!" > /var/www/html/index.html
echo 'server {
        listen 80;
        server_name 54.209.111.179;

        location /redirect_me {
                return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
        }
}' | sudo tee /etc/nginx/sites-available/redirect_me > /dev/null

sudo ln -s /etc/nginx/sites-available/redirect_me /etc/nginx/sites-enabled
sudo nginx -t

sudo service nginx restart
