#!/usr/bin/env bash
#dispalys I am invincible!!! when receiving a SIGTERM signal

function sigterm {
    echo "I am invincible!!!"
}

trap 'sigterm' SIGTERM

while true; do
    echo "To infinity and beyond"
    sleep 2
done    
