#!/usr/bin/env bash
#displays the content of the file /etc/passwd,
#using the while loop + IFS.

IFS=:
while read -r username password uid gid uid_info home shell; do
    echo "The user $username is part of the $gid gang, lives in $home and rides $shell. $uid place is protected by the passcode $password, more info about the user here: $uid_info"
done < /etc/passwd
