#!/usr/bin/env bash
#loops from 1 to 10

VAR=1
while [ $VAR -lt 11 ]; do
    if [ $VAR -eq 4 ]; then
        echo "bad luck"
    elif [ $VAR -eq 8 ]; then
        echo "good luck"
    else
        echo "Best School"
    fi        
    VAR=$((VAR+1))
done
