#!/usr/bin/env bash
#displays the time for 12 hours and 59 minutes

HOUR=0
while [ $HOUR -le 12 ]; do
    echo "Hour: $HOUR"
    MIN=1
    while [ $MIN -le 59 ]; do
        echo "$MIN"
        MIN=$((MIN+1))
    done
    HOUR=$((HOUR+1))
done    
