#!/usr/bin/env bash
#gives you information about the school file.

FILE="school"

if [ -e $FILE ]; then
    echo "$FILE file exists"
else
    echo "$FILE does not exist"
fi
    if [ -s $FILE ]; then
        echo "$FILE file is not empty"
    else
        echo "$FILE file is empty"
    fi        
    if [ -f $FILE ]; then
        echo "$FILE is a regular file"
    fi
