#!/usr/bin/env bash
#gives you information about the school file.

ILE="school"

if [ -e $ILE ]; then
    echo "$ILE file exists"
    if [ -s $ILE ]; then
        echo "$ILE file is not empty"
    else
        echo "$ILE file is empty"
    fi        
    if [ -f $ILE ]; then
        echo "$ILE is a regular file"
    fi
else
    echo "$ILE does not exist"
fi
