#!/usr/bin/env bash
#localhost resolves to 127.0.0.2
#facebook.com resolves to 8.8.8.8.

cp /etc/hosts ~/hosts.new
sed -i "s/127.0.0.2/127.0.0.1/g" ~/hosts.new
#echo "102.132.96.35   facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
